New feature: cloudevents-poem
cloudevents/sdk-rust pull request #159
Opened 2021-11-07 02:28 UTC by sunli829

2021-11-08 22:13 UTC, jcrossley3 commented
Thanks for the contribution! I'm not really familiar with the `in_band_lifetimes` feature, but the stable toolchain obviously doesn't like it. Does poem require it?

2021-11-09 00:42 UTC, sunli829 commented
I'm very sorry, maybe the IDE has added `in_band_lifetimes` to it because of an error, and `poem` can work in stable Rust.

2021-11-10 21:31 UTC, jcrossley3 commented
> I'm very sorry, maybe the IDE has added `in_band_lifetimes` to it because of an error, and `poem` can work in stable Rust.

Awesome, thanks!

Would you mind including a small example in this PR beneath [./example-projects](https://github.com/cloudevents/sdk-rust/tree/master/example-projects). The simpler the better -- just enough to show someone how to get and post a CloudEvent using poem, similar to the apps for actix, axum, and warp in that same dir. It's neat to see the various design choices made by the different frameworks.

Please add a stanza at the bottom of [.github/workflows/rust_tests.yml](https://github.com/cloudevents/sdk-rust/blob/master/.github/workflows/rust_tests.yml) so CI can test the example, too. You can probably just cut and paste the axum one.

Thanks again! I'm looking forward to digging into poem myself at some point!

2021-11-11 01:35 UTC, sunli829 commented
Sorry I forgot to add an example. 😁

2021-11-11 14:14 UTC, jcrossley3 requested changes
I should've been more specific about which example to copy, sorry. The axum GET needs to return an Event like the actix example.

2021-11-11 14:14 UTC, jcrossley3 commented on src/binding/poem/mod.rs
> +//! let app = Route::new().at("/", post(index));
This is cool -- can you include this in the example app, please? It looks like you copied the axum example, which I just realized doesn't return an Event for a GET. It should, just like the actix example. I should've been more specific about which example to use as a template, sorry.

2021-11-11 14:14 UTC, jcrossley3 commented on example-projects/poem-example/src/main.rs
> +    "hello from cloudevents server"
Can you make this return a `Result<Event>` instead, please? See my other comment. Thanks!

2021-11-12 03:37 UTC, sunli829 commented
done.😁

2021-11-13 14:03 UTC, sunli829 reviewed
done! 🙂

2021-11-13 17:59 UTC, jcrossley3 approved these changes

2021-11-13 18:00 UTC, merged

2021-11-13 18:00 UTC, jcrossley3 commented
Thank you!