CI Improvements
cloudevents/sdk-rust pull request #96
Opened 2020-10-30 08:10 UTC by slinkydeveloper

Fix #67

* Now CI run example builds
* Now CI tests on each pr the different matrix nightly/stable and targets
* Added clippy to the lints

Signed-off-by: Francesco Guardiani <francescoguard@gmail.com>

2020-10-30 08:24 UTC, slinkydeveloper commented
I'm gonna fix all the lint warnings in a followup PR, I want to perform just CI changes in this one

2020-10-30 09:02 UTC, slinkydeveloper commented
Stable fails because rdkafka example is broken, it's fixed in #95

2020-11-02 07:49 UTC, Lazzaretti requested changes

2020-11-02 07:49 UTC, Lazzaretti commented on .github/workflows/rust_tests.yml
> +        args: --target ${{ matrix.target }} --manifest-path ./example-projects/actix-web-example/Cargo.toml
add a newline at the end

2020-11-02 08:02 UTC, Lazzaretti approved these changes

2020-11-02 08:06 UTC, merged